import { NextResponse } from "next/server";
import type { Market } from "@/types";

// Mock market data for development - in production this syncs from real APIs
const MOCK_MARKETS: Market[] = [
  {
    id: "kalshi_pres_2028",
    externalId: "PRES-2028-DEM",
    platform: "KALSHI",
    title: "Will a Democrat win the 2028 presidential election?",
    description: "Resolves Yes if the Democratic candidate wins the 2028 US presidential election.",
    category: "Politics",
    yesPrice: 0.52,
    noPrice: 0.48,
    volume24h: 284000,
    liquidity: 1200000,
    closingTime: new Date("2028-11-03"),
    resolvedAt: null,
    resolution: null,
    status: "ACTIVE",
    matchedMarketId: "poly_pres_2028",
    lastUpdated: new Date(),
  },
  {
    id: "poly_pres_2028",
    externalId: "0x1234abcd",
    platform: "POLYMARKET",
    title: "Democrat wins 2028 presidential election",
    description: "Will the Democratic nominee win the 2028 presidential election?",
    category: "Politics",
    yesPrice: 0.49,
    noPrice: 0.51,
    volume24h: 520000,
    liquidity: 3400000,
    closingTime: new Date("2028-11-03"),
    resolvedAt: null,
    resolution: null,
    status: "ACTIVE",
    matchedMarketId: "kalshi_pres_2028",
    lastUpdated: new Date(),
  },
  {
    id: "kalshi_btc_100k",
    externalId: "BTC-100K-2026",
    platform: "KALSHI",
    title: "Will Bitcoin exceed $100,000 by end of 2026?",
    description: "Resolves Yes if BTC price exceeds $100,000 USD at any point before Dec 31, 2026.",
    category: "Crypto",
    yesPrice: 0.72,
    noPrice: 0.28,
    volume24h: 156000,
    liquidity: 890000,
    closingTime: new Date("2026-12-31"),
    resolvedAt: null,
    resolution: null,
    status: "ACTIVE",
    matchedMarketId: "poly_btc_100k",
    lastUpdated: new Date(),
  },
  {
    id: "poly_btc_100k",
    externalId: "0x5678efgh",
    platform: "POLYMARKET",
    title: "Bitcoin above $100K in 2026",
    description: "Will Bitcoin trade above $100,000 before end of 2026?",
    category: "Crypto",
    yesPrice: 0.68,
    noPrice: 0.32,
    volume24h: 340000,
    liquidity: 2100000,
    closingTime: new Date("2026-12-31"),
    resolvedAt: null,
    resolution: null,
    status: "ACTIVE",
    matchedMarketId: "kalshi_btc_100k",
    lastUpdated: new Date(),
  },
  {
    id: "kalshi_fed_rate",
    externalId: "FED-RATE-CUT-MAR26",
    platform: "KALSHI",
    title: "Will the Fed cut rates in March 2026?",
    description: "Resolves Yes if the FOMC cuts the federal funds rate at the March 2026 meeting.",
    category: "Economics",
    yesPrice: 0.35,
    noPrice: 0.65,
    volume24h: 89000,
    liquidity: 450000,
    closingTime: new Date("2026-03-20"),
    resolvedAt: null,
    resolution: null,
    status: "ACTIVE",
    matchedMarketId: "poly_fed_rate",
    lastUpdated: new Date(),
  },
  {
    id: "poly_fed_rate",
    externalId: "0x9abcdef0",
    platform: "POLYMARKET",
    title: "Fed rate cut in March 2026",
    description: "Will the Federal Reserve lower interest rates at the March 2026 FOMC meeting?",
    category: "Economics",
    yesPrice: 0.31,
    noPrice: 0.69,
    volume24h: 125000,
    liquidity: 780000,
    closingTime: new Date("2026-03-20"),
    resolvedAt: null,
    resolution: null,
    status: "ACTIVE",
    matchedMarketId: "kalshi_fed_rate",
    lastUpdated: new Date(),
  },
  {
    id: "kalshi_ai_agi",
    externalId: "AGI-2026",
    platform: "KALSHI",
    title: "Will an AI system pass a comprehensive AGI test by end of 2026?",
    description: "Resolves Yes based on the criteria defined by the designated evaluation board.",
    category: "Technology",
    yesPrice: 0.08,
    noPrice: 0.92,
    volume24h: 45000,
    liquidity: 230000,
    closingTime: new Date("2026-12-31"),
    resolvedAt: null,
    resolution: null,
    status: "ACTIVE",
    matchedMarketId: null,
    lastUpdated: new Date(),
  },
  {
    id: "poly_recession",
    externalId: "0xdeadbeef",
    platform: "POLYMARKET",
    title: "US recession in 2026",
    description: "Will the NBER declare a US recession starting in 2026?",
    category: "Economics",
    yesPrice: 0.22,
    noPrice: 0.78,
    volume24h: 198000,
    liquidity: 1500000,
    closingTime: new Date("2027-06-30"),
    resolvedAt: null,
    resolution: null,
    status: "ACTIVE",
    matchedMarketId: null,
    lastUpdated: new Date(),
  },
  {
    id: "kalshi_sp500",
    externalId: "SP500-6000-2026",
    platform: "KALSHI",
    title: "Will the S&P 500 close above 6,000 on Dec 31, 2026?",
    description: "Resolves based on the closing value of the S&P 500 index.",
    category: "Finance",
    yesPrice: 0.61,
    noPrice: 0.39,
    volume24h: 210000,
    liquidity: 950000,
    closingTime: new Date("2026-12-31"),
    resolvedAt: null,
    resolution: null,
    status: "ACTIVE",
    matchedMarketId: "poly_sp500",
    lastUpdated: new Date(),
  },
  {
    id: "poly_sp500",
    externalId: "0xcafebabe",
    platform: "POLYMARKET",
    title: "S&P 500 above 6,000 at end of 2026",
    description: "Will the S&P 500 close above 6,000 on the last trading day of 2026?",
    category: "Finance",
    yesPrice: 0.57,
    noPrice: 0.43,
    volume24h: 175000,
    liquidity: 1100000,
    closingTime: new Date("2026-12-31"),
    resolvedAt: null,
    resolution: null,
    status: "ACTIVE",
    matchedMarketId: "kalshi_sp500",
    lastUpdated: new Date(),
  },
  {
    id: "kalshi_eth_merge",
    externalId: "ETH-5K-2026",
    platform: "KALSHI",
    title: "Will Ethereum exceed $5,000 in 2026?",
    description: "Resolves Yes if ETH trades above $5,000 at any point in 2026.",
    category: "Crypto",
    yesPrice: 0.42,
    noPrice: 0.58,
    volume24h: 67000,
    liquidity: 340000,
    closingTime: new Date("2026-12-31"),
    resolvedAt: null,
    resolution: null,
    status: "ACTIVE",
    matchedMarketId: "poly_eth_5k",
    lastUpdated: new Date(),
  },
  {
    id: "poly_eth_5k",
    externalId: "0xfeedface",
    platform: "POLYMARKET",
    title: "Ethereum above $5,000 in 2026",
    description: "Will ETH price exceed $5,000 before the end of 2026?",
    category: "Crypto",
    yesPrice: 0.38,
    noPrice: 0.62,
    volume24h: 92000,
    liquidity: 560000,
    closingTime: new Date("2026-12-31"),
    resolvedAt: null,
    resolution: null,
    status: "ACTIVE",
    matchedMarketId: "kalshi_eth_merge",
    lastUpdated: new Date(),
  },
];

export async function GET() {
  return NextResponse.json({
    markets: MOCK_MARKETS,
    syncedAt: new Date().toISOString(),
    count: MOCK_MARKETS.length,
  });
}

export async function POST() {
  // In production: trigger background sync from both APIs
  return NextResponse.json({
    status: "sync_initiated",
    message: "Market catalog sync started",
    estimatedMarkets: MOCK_MARKETS.length,
  });
}
